hardware_specs <- tagList(
  h3("Housing & Design"),
  selectizeInput(
    "hardware_device_mounting",
    "Optionally select how the device needs to be mountable",
    choices = c("wristband", "necklace", "spectacle-frame holder", "clip", "head-band"),
    multiple = TRUE,
    options  = list(placeholder = "Select required mounting options"),
    width = "100%"
  ),
  selectizeInput(
    "hardware_material",
    "Housing material(s)",
    choices  = c("Plastic", "Aluminium", "Stainless steel", "Silicone", "Rubber", "Fabric", "Other"),
    multiple = TRUE,
    options  = list(placeholder = "Optionally select acceptable materials"),
    width = "100%"
  ),
  div("What do you consider maximum dimensions?"),
  layout_column_wrap(
    sliderInput(
      "hardware_device_width",
      "Width",
      min = 0.5, max = 10, value = 5, step = 0.5
    ),
    sliderInput(
      "hardware_device_depth",
      "Depth",
      min = 0.5, max = 10, value = 5, step = 0.5
    ),
    sliderInput(
      "hardware_device_height",
      "Height",
      min = 0.5, max = 10, value = 2.5, step = 0.5
    ),
  ),
  radioButtons(
    "hardware_device_size_unit",
    label = "Values in",
    inline = TRUE,
    choiceNames = c("centimeters (cm)", "inches (in)"),
    choiceValues = c("cm", "in"),
    width = "100%"
  ),
  numericInput("weight_max_g", 
               "Maximum device weight (g)", 
               value = NULL, 
               min = 0, step = 1,
               width = "100%"),
  textAreaInput("hardware_design_notes", 
                "Special design considerations", 
                placeholder = "e.g., 'needs to be centered' for spectacle-mount",
                width = "100%"),
  h3("Measurement & Sensors"),
  h5("Spectral characteristics"),
  sliderInput("spec_wavelength_range",
              "Minimum and Maximum detectable wavelength",
              min = 100, 
              max = 1000,
              value = c(380, 780), step = 5,
              post = " nm",
              width = "100%"),
  numericInput("min_spectral_channels", 
               "Minimum number of spectral sensor channels", 
               width = "100%",
               value = NULL, 
               min = 1, 
               step = 1),
  checkboxInput("include_ir", 
                "Requirement of IR sensing ≥ 1000nm", 
                value = FALSE,
                width = "100%"
                ),
  h5("Operating range"),
  sliderTextInput("spec_illuminance_range",
                  "Operating range (with specified error)",
                  choices = c("10<sup>-2</sup>", "10<sup>-1</sup>", "1", "10", 
                              "10<sup>2</sup>", "10<sup>3</sup>", "10<sup>4</sup>", 
                              "10<sup>5</sup>"), 
                  selected = c("1", "10<sup>4</sup>"), grid = TRUE, post = " lx",
                  width = "100%"),
  numericInput("measurement_error_pct", 
               "Acceptable measurement error within operating range (%)", 
               value = NULL, 
               width = "100%",
               min = 0, 
               max = 100, 
               step = 0.1),
  h5("Spatial detection"),
  checkboxInput("require_cosine", 
                "Cosine‑corrected (lambertian) response", 
                width = "100%",
                value = FALSE),
  numericInput("field_of_view_deg", 
               "Field of view (°)", 
               value = NULL, 
               min = 0, 
               width = "100%",
               max = 180, 
               step = 1),
  h5("Other modalities"),
  selectizeInput(
    inputId = "other_modalities",
    label   = "Other necessary measurement modalities",
    choices = c("Distance/Proximity", 
                "Accelerometer (3-axis)", 
                "Gyroscope", 
                "Spatial resolution",
                "Altimeter/Barometer",
                "Skin Temperature",
                "Ambient Temperature",
                "Skin Conductance"),
    selected  = NULL,
    multiple = TRUE,
    width = "100%",
    options   = list(placeholder = "Select other modalities (optional)")
  ),
  h3("Battery & Storage"),
  sliderTextInput(
    "hardware_battery_capacity",
    grid = TRUE,
    width = "100%",
    "How long does the device need to run on a single battery charge?", 
    choices = c("<1 day", "≥1 day", "≥1 week", "≥2 weeks", "≥1 month", ">1 year"), 
    selected = "≥2 weeks"
  ),
  layout_column_wrap(
  numericInput("on_device_days", 
               "Required minimum on-device data storage capacity (days)", 
               width = "100%",
               value = NULL, 
               min = 1, 
               step = 1),
  sliderTextInput(
    "hardware_recording_interval",
    grid = TRUE,
    width = "100%",
    "What would be (closest to) the typical recording interval?", 
    choices = c("1s", "10s", "30s", "1min", "5min", "15min", "30min", "1h", "2h"), 
    selected = "10s"
  )),
  htmlOutput("storage_days", container = p),
  h3("Operating Environment"),
  sliderInput("op_temp",
              "Operating temperature (°C)",
              min = -30, 
              max = 60,
              value = c(-10, 45), step = 5,
              post = " °C",
              width = "100%"),  
  sliderInput("op_humidity",
              "Operating humidity, relative (% RH)",
              min = 0, 
              max = 100,
              value = c(20, 95), step = 5,
              post = " % RH",
              width = "100%"),
  selectizeInput(
    inputId = "ip_rating",
    label   = tagList("Ingress Protection (IP) rating", icon("info-circle")),
    choices = c("", "IPX0", "IPX1", "IPX2", "IPX3", "IPX4", "IP55", "IP64", "IP65", "IP66", "IP67", "IP68"),
    selected  = NULL,
    width = "100%",
    options   = list(placeholder = "Select IP rating (optional)")
  ) |> 
    tooltip(
      p("IPXY: X = solids (0–6), Y = water (0–8)."),
      p("Solids – 0 none, 1 >50 mm, 2 >12.5 mm, 3 >2.5 mm, 4 >1 mm, 5 dust‑protected, 6 dust‑tight."),
      p("Water – 0 none, 1 drips, 2 drips @15°, 3 spray, 4 splash, 5 jets, 6 powerful jets, 7 immersion ≤1 m, 8 immersion >1 m."),
      placement = "right",
      options   = list(container = "body")
    ),
  selectizeInput("sports_rating", 
                 "Required device suitability for activities",
                 choices = c("Showering", "Biking", "Swimming", "Running", 
                             "Contact sports", "Climbing"),
                 selected = NULL,
                 options   = list(placeholder = "Select activities (optional)"),
                 multiple = TRUE,
                 width = "100%"),
  h3("Controls & Indicators"),
  checkboxInput("event_button", 
                "Require event marker button", 
                value = FALSE,
                width = "100%"),  
  checkboxInput("btn_start_stop", 
                "Require dedicated start/stop recording button", 
                value = FALSE,
                width = "100%"),  
  selectizeInput("status_indicators", 
                 "Required user feedback indicators (e.g. status light)",
                 choices = c("Charging", "Low battery", "Recording", "Error"),
                 selected = NULL,
                 multiple = TRUE,
                 options   = list(placeholder = "Select status indicators (optional)"),
                 width = "100%"),  
  h3("Connectivity & I/O"),
  selectizeInput("physical_ports", 
                 width = "100%",
                 "Acceptable connector(s) for charging/sync",
                 choices = c("USB‑C", 
                             "Micro‑USB", 
                             "Proprietary connector", 
                             "Docking station",
                             "Wireless charging"),
                 options   = list(placeholder = "Accept possibilites for charging & sync (optional)"),
                 multiple = TRUE,
                 selected = NULL),
  selectizeInput("wireless_connectivity", 
                 "Required wireless connectivity",
                 multiple = TRUE,
                 width = "100%",
                 options   = list(placeholder = "Require wireless connectivity (optional)"),
                 choices = c("Bluetooth", "Wi‑Fi", "NFC"),
                 selected = NULL),
  h3("Other hardware considerations"),
  numericInput("min_sampling_rate_hz", 
               "Highest possible sampling rate (Hz)", 
               width = "100%",
               value = NULL, 
               min = 1, 
               step = 1),
  textAreaInput("hardware_other notes", 
                "Other hardware considerations", 
                placeholder = "Add hardware requirements or important considerations that are not covered by the form",
                width = "100%"),
)